### ISSUE TITLE
Error coming from setup_pte_fun()

### ISSUE THREAD

**Issue by sljardine** [bcallaway11/ife#2]
Hello,

I am interested in the IFE framework you've developed and started to explore this R package. It looks like the original example is no longer working. Perhaps due to changes in the `pte` package. Screenshot attached.

Thanks!

<img width="581" alt="Screenshot 2024-08-06 at 11 11 21 AM" src="https://github.com/user-attachments/assets/5bad604d-d5e5-4bff-acce-a517a07bffe8">

**Comment by bcallaway11** [comment]
Yes, thanks for pointing this out.  I am pretty sure I know the source of this issue.  I will update as soon as possible.

**Comment by tfmrs** [comment]
Dear Mr. Callaway, thanks a lot for your IFE routine. I am having the same issue with the orig2t not being found. Could I kindly ask about how to fix it? Thanks a lot.

**Comment by bcallaway11** [comment]
Hello @sljardine and @tfmrs:

The issue should be fixed now.  Please run `devtools::update_packages()` to get the updated version of the `ife` package (you should get up to version 0.0.902), and then please accept when it prompts you to update the `BMisc` package (for that one, you should get version 1.4.7.  That is not available yet on CRAN, but you can get it from GitHub.

I am optimistic that this will fix the issues that you are running into, but please let me know if you still encounter any issues.

**Comment by sljardine** [comment]
Hello @bcallaway11,

Thanks for your reply. I was able to get the example to run after attaching both the `ife` and `BMisc` packages (using the `library()` function). Although running `devtools::update_packages()` to get the updated version of `ife` did not prompt me to update `BMisc`, I was able to download the new version directly from GitHub. 

Thanks again!

**Comment by bcallaway11** [comment]
Great!  Glad to hear this worked (and for the clarification on updating packages).  I'll going to close this issue now, but please keep me posted if you run into other issues.

Brant
